In [21]:
import numpy as np
import time
import sys

#### uses less memory

# without numpy
ll = range(1000)
print 'Python list of 1000 elements use memory of', sys.getsizeof(ll[0]) * len(ll)

# numpy
array = np.arange(1000)
print 'Numpy array of 1000 elements use memory of', array.size * array.itemsize, '\n'

Python list of 1000 elements use memory of 24000
Numpy array of 1000 elements use memory of 8000 



In [22]:
#### fast

SIZE = 1000

l1 = range(SIZE)
l2 = range(SIZE)

a1 = np.arange(SIZE)
a2 = np.arange(SIZE)

start = time.time()
result = [(x+y) for x,y in zip(l1, l2)]
print 'Python list took: ', (time.time() - start)*10000      # 1M

start = time.time()
result = a1 + a2
print 'Numpy took: ', (time.time() - start)*10000,'\n'

Python list took:  9.54866409302
Numpy took:  3.03983688354 



In [23]:
## basic array operations
arr1 = np.array([1,2,4,5,6])
print arr1.ndim     # dimension

arr2 = np.array([[1,2],[3,4],[6,5]])
print arr2.ndim

print 'Each item size: ', arr2.itemsize
print 'datatype of each element: ', arr2.dtype,'\n'

1
2
Each item size:  8
datatype of each element:  int64 



In [25]:
arr3 = np.array([[1,2], [3,4], [5,6]], dtype=np.float64)
print arr3

print arr3.size     # number of elements
print arr3.shape        # matrix size

[[1. 2.]
 [3. 4.]
 [5. 6.]]
6
(3, 2)


In [27]:
arr4 = np.arange(1,10,2)
print arr4,'\n'

arr5 = arr3.reshape(2,3)        # reshape the matrix
print arr5,'\n'

arr6 = arr5.ravel()             # flaten the matrix
print arr6

[1 3 5 7 9] 

[[1. 2. 3.]
 [4. 5. 6.]] 

[1. 2. 3. 4. 5. 6.]


In [31]:
print 'max: ',arr3.max()
print 'min:',arr3.min()
print 'sum of columns', arr3.sum(axis=0)      # sum of columns
print 'sum of rows', arr3.sum(axis=1)      # sum of rows

print arr5[0,1]        # row, column
print arr5[0:2, 1]      # 1st index element of 0,1 rows

print arr5[-1, 0:2],'\n'      # last row
print arr5[:,0:2], '\n'

max:  6.0
min: 1.0
sum of columns [ 9. 12.]
sum of rows [ 3.  7. 11.]
2.0
[2. 5.]
[4. 5.] 

[[1. 2.]
 [4. 5.]] 



In [33]:
a1 = np.arange(6).reshape(3,2)
b1 = np.arange(6).reshape(3,2)
print a1,'\n'
print b1,'\n'

c1 = np.vstack((a1,b1))
# c1 = np.hstack((a1,b1))
print c1

[[0 1]
 [2 3]
 [4 5]] 

[[0 1]
 [2 3]
 [4 5]] 

[[0 1]
 [2 3]
 [4 5]
 [0 1]
 [2 3]
 [4 5]]
